import yfinance as yf
import json
import os
import concurrent.futures

NIFTY_50 = "RELIANCE.NS, TCS.NS, HDFCBANK.NS, BHARTIARTL.NS, ICICIBANK.NS, INFOSYS.NS, SBIN.NS, HINDUNILVR.NS, BAJFINANCE.NS, AXISBANK.NS, KOTAKBANK.NS, LT.NS, HCLTECH.NS, MARUTI.NS, SUNPHARMA.NS, ASIANPAINT.NS, TITAN.NS, NESTLEIND.NS, WIPRO.NS, ONGC.NS, NTPC.NS, POWERGRID.NS, ULTRACEMCO.NS, JSWSTEEL.NS, TATASTEEL.NS, TECHM.NS, ADANIENT.NS, ADANIPORTS.NS, COALINDIA.NS, BAJAJ-AUTO.NS, BAJAJFINSV.NS, DRREDDY.NS, EICHERMOT.NS, GRASIM.NS, HEROMOTOCO.NS, HINDALCO.NS, INDUSINDBK.NS, ITC.NS, JIOFIN.NS, M&M.NS, APOLLOHOSP.NS, BPCL.NS, BRITANNIA.NS, CIPLA.NS, DIVISLAB.NS, TATACONSUM.NS, TRENT.NS, SHRIRAMFIN.NS, SBILIFE.NS, HDFCLIFE.NS"
NIFTY_NEXT_50 = "ADANIGREEN.NS, ADANITRANS.NS, AMBUJACEM.NS, BANDHANBNK.NS, BERGEPAINT.NS, BEL.NS, CHOLAFIN.NS, COLPAL.NS, DABUR.NS, DLF.NS, GAIL.NS, GODREJCP.NS, HAVELLS.NS, ICICIGI.NS, ICICIPRULI.NS, INDUSTOWER.NS, IRCTC.NS, JINDALSTEL.NS, JUBLFOOD.NS, LICINDIAETF.NS, LUPIN.NS, MANKIND.NS, MCDOWELL-N.NS, MUTHOOTFIN.NS, NAUKRI.NS, OBEROIRLTY.NS, OFSS.NS, PAGEIND.NS, PATANJALI.NS, PERSISTENT.NS, PIDILITIND.NS, PIIND.NS, PGHH.NS, POLYCAB.NS, RECLTD.NS, SAIL.NS, SHREECEM.NS, SIEMENS.NS, SRF.NS, TATACOMM.NS, TORNTPHARM.NS, TVSMOTOR.NS, UBL.NS, UNITDSPR.NS, VBL.NS, VEDL.NS, VOLTAS.NS, ZOMATO.NS, ZYDUSLIFE.NS, NHPC.NS"
NIFTY_MIDCAP_150 = "ABCAPITAL.NS, ABFRL.NS, AIAENG.NS, AJANTPHARM.NS, ALKEM.NS, ANGELONE.NS, APLAPOLLO.NS, APOLLOTYRE.NS, ASHOKLEY.NS, ASTRAL.NS, ATUL.NS, AUBANK.NS, AUROPHARMA.NS, AVENUES.NS, BALKRISIND.NS, BATAINDIA.NS, BHARATFORG.NS, BHEL.NS, BIOCON.NS, BLUEDART.NS, BOSCHLTD.NS, BSE.NS, CAMS.NS, CANFINHOME.NS, CASTROLIND.NS, CESC.NS, CGPOWER.NS, CHAMBLFERT.NS, COFORGE.NS, CONCOR.NS, CRISIL.NS, CROMPTON.NS, CUB.NS, CUMMINSIND.NS, DEEPAKNTR.NS, DELHIVERY.NS, DELTACORP.NS, DIXON.NS, EIDPARRY.NS, ELGIEQUIP.NS, EMAMILTD.NS, ENDURANCE.NS, ENGINERSIN.NS, ESCORTS.NS, EXIDEIND.NS, FEDERALBNK.NS, FINPIPE.NS, FLUOROCHEM.NS, FORTIS.NS, GLENMARK.NS, GMRINFRA.NS, GNFC.NS, GODFRYPHLP.NS, GODREJIND.NS, GPPL.NS, GRANULES.NS, GSPL.NS, HAPPSTMNDS.NS, HFCL.NS, HINDCOPPER.NS, HINDPETRO.NS, HONAUT.NS, IDFCFIRSTB.NS, IEX.NS, IFCI.NS, IIFL.NS, INDHOTEL.NS, INDIAMART.NS, INDIANB.NS, INDIGO.NS, IOC.NS, IPCALAB.NS, IRFC.NS, JKCEMENT.NS, JKPAPER.NS, JMFINANCIAL.NS, JSL.NS, JUBLINGREA.NS, KAJARIACER.NS, KALPATPOWR.NS, KANSAINER.NS, KARURVYSYA.NS, KEI.NS, KPITTECH.NS, KRBL.NS, KSCL.NS, LAURUSLABS.NS, LICHSGFIN.NS, LINDEINDIA.NS, LTIM.NS, LTTS.NS, LUXIND.NS, MAHSEAMLES.NS, MANAPPURAM.NS, MARICO.NS, MCX.NS, METROPOLIS.NS, MFSL.NS, MGL.NS, MINDTREE.NS, MOTILALOFS.NS, MRF.NS, MUTHOOTFIN.NS, NATCOPHARM.NS, NAVINFLUOR.NS, NCC.NS, NETWORK18.NS, NLCINDIA.NS, NMDC.NS, NUVOCO.NS, OBEROIRLTY.NS, OIL.NS, OLECTRA.NS, PNBHOUSING.NS, POLICYBZR.NS, POLYMED.NS, PRAJIND.NS, PRINCEPIPE.NS, PSB.NS, PVRINOX.NS, RADICO.NS, RAILTEL.NS, RAJESHEXPO.NS, RAMCOCEM.NS, RATNAMANI.NS, RAYMOND.NS, REDINGTON.NS, RELAXO.NS, RKFORGE.NS, ROSSARI.NS, ROUTE.NS, RVNL.NS, SAFARI.NS, SANOFI.NS, SAPPHIRE.NS, SCHAEFFLER.NS, SHYAMMETL.NS, SKFINDIA.NS, SOBHA.NS, SOLARA.NS, SONACOMS.NS, STARHEALTH.NS, STLTECH.NS, SUMICHEM.NS, SUNDARMFIN.NS, SUNDRMFAST.NS, SUNTV.NS, SUPPETRO.NS, SUPREMEIND.NS, SUZLON.NS, SWANENERGY.NS, SYMPHONY.NS, TANLA.NS, TATAELXSI.NS, TATAINVEST.NS, TATAPOWER.NS, TCNSBRANDS.NS, TEAMLEASE.NS, THERMAX.NS, TIINDIA.NS, TIMKEN.NS, TRIDENT.NS, TRITURBINE.NS, TTKPRESTIG.NS"
NIFTY_SMALLCAP_250 = "AARTIDRUGS.NS, AARTIIND.NS, ABFRL.NS, ACCELYA.NS, ACE.NS, ACRYSIL.NS, ADANIPOWER.NS, ADFFOODS.NS, AEGISCHEM.NS, AFFLE.NS, AGROPHOS.NS, AIIL.NS, AJAXENG.NS, AKZOINDIA.NS, ALEMBICLTD.NS, ALEXISR.NS, ALKYLAMINE.NS, ALLCARGO.NS, ALMONDZ.NS, ALOKINDS.NS, AMARAJABAT.NS, AMBER.NS, AMCREDIFO.NS, AMIORG.NS, ANANTRAJ.NS, ANDHRSUGAR.NS, ANURAS.NS, APARINDS.NS, APCOTEXIND.NS, APTECHT.NS, ARCHIDPLY.NS, ARCOTECH.NS, ARSHIYA.NS, ARVIND.NS, ASAHIINDIA.NS, ASALCBR.NS, ASHIANA.NS, ASHIMASYN.NS, ASIANTILES.NS, ASKAUTOLTD.NS, ASTRAZEN.NS, ATGL.NS, ATUL.NS, AUTOAXLES.NS, AVANTIFEED.NS, AXISCADES.NS, BAJAJHIND.NS, BAJAJHLDNG.NS, BALMLAWRIE.NS, BANARISUG.NS, BANCOINDIA.NS, BASF.NS, BAYERCROP.NS, BBTC.NS, BEARDSELL.NS, BEDMUTHA.NS, BEML.NS, BFINVEST.NS, BGRENERGY.NS, BHAGERIA.NS, BHAGINFOTEC.NS, BHARATWIRE.NS, BHEEMITE.NS, BIKAJI.NS, BIRLACORPN.NS, BLISSGVS.NS, BOROLTD.NS, BORORENEW.NS, BRIGADE.NS, BSOFT.NS, CAPLIPOINT.NS, CARBORUNIV.NS, CCL.NS, CENTENKA.NS, CENTEXT.NS, CENTRUM.NS, CERA.NS, CHEMFAB.NS, CHEMPLASTS.NS, CHEVIOT.NS, CIEINDIA.NS, CLEAN.NS, CLNINDIA.NS, CMICABLES.NS, COALINDIA.NS, COCHINSHIP.NS, COMPUSOFT.NS, CONFIPET.NS, CONTROLPR.NS, CORDS.NS, CRAFTSMAN.NS, CREDITACC.NS, DALBHARAT.NS, DAMODARIND.NS, DATAMATICS.NS, DCB.NS, DCW.NS, DELCRED.NS, DHUNSERI.NS, DIGISPICE.NS, DOLLAR.NS, DPWIRES.NS, DREDGECORP.NS, DWARKESH.NS, DYNAMATECH.NS, ECLERX.NS, EDELWEISS.NS, ELGI.NS, EMS.NS, EPIGRAL.NS, EQUITASBNK.NS, ESABINDIA.NS, FINEORG.NS, FINOLEX.NS, FMGOETZE.NS, FOSECOIND.NS, FUSION.NS, GALAXYSURF.NS, GARFIBRES.NS, GATEWAY.NS, GENUSPOWER.NS, GHCL.NS, GLOBUSSPR.NS, GMMPFAUDLR.NS, GOCOLORS.NS, GODREJAGRO.NS, GOLDIAM.NS, GPIL.NS, GREENPLY.NS, GREENPANEL.NS, GESHIP.NS, GSFC.NS, GTPL.NS, GUJALKALI.NS, GULFOILLUB.NS, GULFPETRO.NS, HAPPYFORGE.NS, HARDWYN.NS, HARIOMPIPE.NS, HCC.NS, HEGDE.NS, HEIDELBERG.NS, HEG.NS, HEMIPROP.NS, HERITGFOOD.NS, HIKAL.NS, HIMS.NS, HINDWAREAP.NS, HNDFDS.NS, HOMEFIRST.NS, HPL.NS, HTMEDIA.NS, HUBTOWN.NS, HUHTAMAKI.NS, IBREALEST.NS, ICRA.NS, IDBI.NS, IDFC.NS, IDFCFIRSTB.NS, IGPL.NS, IIFLSEC.NS, IMFA.NS, INDIACEM.NS, INDIAGLYCO.NS, INDIAINFO.NS, INDNIPPON.NS, INDORAMA.NS, INDOSTAR.NS, INFIBEAM.NS, INTELLECT.NS, INTERGLOBE.NS, IOL.NS, ISGEC.NS, ITI.NS, JBCHEPHARM.NS, JBMA.NS, JETAIRWAYS.NS, JKIL.NS, JKLAKSHMI.NS, JKTYRE.NS, JMFINANCIAL.NS, JPASSOCIAT.NS, JPPOWER.NS, JUSTDIAL.NS"

def parse_csv(csv_str):
    return [x.strip() for x in csv_str.split(',') if x.strip()]

indexes = {
    "Nifty 50": parse_csv(NIFTY_50),
    "Nifty Next 50": parse_csv(NIFTY_NEXT_50),
    "Nifty Midcap 150": parse_csv(NIFTY_MIDCAP_150),
    "Nifty Smallcap 250": parse_csv(NIFTY_SMALLCAP_250)
}

all_stocks = []
for idx_name, syms in indexes.items():
    for sym in syms:
        # avoid duplicates
        if not any(s['symbol'] == sym for s in all_stocks):
            all_stocks.append({"symbol": sym, "index": idx_name})

print(f"Total unique stocks: {len(all_stocks)}")

def fetch_info(stock):
    sym = stock["symbol"]
    try:
        t = yf.Ticker(sym)
        info = t.info
        stock["name"] = info.get("longName", info.get("shortName", sym.replace('.NS', '')))
        stock["sector"] = info.get("sector", "Unknown Sector")
        stock["industry"] = info.get("industry", "Unknown Industry")
    except Exception as e:
        stock["name"] = sym.replace('.NS', '')
        stock["sector"] = "Unknown Sector"
        stock["industry"] = "Unknown Industry"
    return stock

with concurrent.futures.ThreadPoolExecutor(max_workers=20) as executor:
    results = list(executor.map(fetch_info, all_stocks))

out_path = os.path.join(os.path.dirname(__file__), "data", "nse_stocks.json")
with open(out_path, "w") as f:
    json.dump(results, f, indent=2)

print(f"Saved to {out_path}")
